version: "3.9"
services:
  app:
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URL: ${DATABASE_URL}
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NEXT_PUBLIC_WS_URL: ${NEXT_PUBLIC_WS_URL}
    working_dir: /app
    ports:
      - "3000:3000"
    image: t3-app
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - S_MAXAGE=${S_MAXAGE}
      - STALE_WHILE_REVALIDATE=${STALE_WHILE_REVALIDATE}
      - SAMPLER_RATIO=${SAMPLER_RATIO}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
      - BUCKET_NAME=${BUCKET_NAME}
      - URL_EXPIRATION_TIME=${URL_EXPIRATION_TIME}
      - BUCKET_CORS_EXPIRATION_TIME=${BUCKET_CORS_EXPIRATION_TIME}
